version: "1"
services:
        hello-world-api:
            container_name: documents-api
            image: latest/documents-api
            restart: always
            build: .
            ports:
              - "8080:8080"
            links:
              - mongo
  
        mongo:
              container_name: mongo
              image: mongo
              volumes:
                - ./data:/data/db
              ports:
                - '27017:27017'