version: "1"
services:
        tasks-app:
            container_name: documents-app
            image: latest/documents-app
            restart: always
            build: .
            ports:
              - "4000:4000"
            links:
              - mongo
        mongo:
              container_name: mongo
              image: mongo
              volumes:
                - ./data:/data/db
              ports:
                - '27018:27017'